AppBundle\Entity\Ad:
    type: entity
    table: ad
    indexes:
        id_user:
            columns:
                - id_user
        id_subject:
            columns:
                - id_subject
        id_services:
            columns:
                - id_services
    id:
        idAd:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_ad
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
        adText:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: ad_text
        price:
            type: integer
            nullable: false
            options:
                unsigned: false
        currency:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        durability:
            type: integer
            nullable: false
            options:
                unsigned: false
        value:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        dateServ:
            type: date
            nullable: false
            column: date_serv
    manyToOne:
        idServices:
            targetEntity: AdServices
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_services:
                    referencedColumnName: id_services
            orphanRemoval: false
        idSubject:
            targetEntity: Subjects
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_subject:
                    referencedColumnName: id_subject
            orphanRemoval: false
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
