AppBundle\Entity\AdQuery:
    type: entity
    table: ad_query
    indexes:
        id_ad:
            columns:
                - id_ad
        id_user:
            columns:
                - id_user
        id_teacher:
            columns:
                - id_teacher
    id:
        idQuery:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_query
            generator:
                strategy: IDENTITY
    fields:
        confirm:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idAd:
            targetEntity: Ad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ad:
                    referencedColumnName: id_ad
            orphanRemoval: false
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
        idTeacher:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_teacher:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
