AppBundle\Entity\Subjects:
    type: entity
    table: subjects
    indexes:
        id_type:
            columns:
                - id_type
    id:
        idSubject:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_subject
            generator:
                strategy: IDENTITY
    fields:
        subject:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        idType:
            targetEntity: SubjectType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_type:
                    referencedColumnName: id_stype
            orphanRemoval: false
    lifecycleCallbacks: {  }
