AppBundle\Entity\SubjectType:
    type: entity
    table: subject_type
    id:
        idStype:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_stype
            generator:
                strategy: IDENTITY
    fields:
        stype:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
