AppBundle\Entity\Users:
    type: entity
    table: users
    id:
        idUser:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        patronymic:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        surname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        login:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        rating:
            type: integer
            nullable: false
            options:
                unsigned: false
        regdate:
            type: date
            nullable: false
        photo:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        about:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
