AppBundle\Entity\уomplaints:
    type: entity
    table: сomplaints
    indexes:
        id_sender:
            columns:
                - id_sender
        id_ad:
            columns:
                - id_ad
        id_mes:
            columns:
                - id_mes
    id:
        idComplaints:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_complaints
            generator:
                strategy: IDENTITY
    fields:
        idAd:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: id_ad
        idMes:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: id_mes
        act:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        dateAct:
            type: date
            nullable: false
            column: date_act
        dateEnd:
            type: date
            nullable: false
            column: date_end
        dateComplaints:
            type: date
            nullable: false
            column: date_complaints
    manyToOne:
        idSender:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sender:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
